### ISSUE TITLE
Code locator provider

### ISSUE THREAD

**Issue by pathmapper** [thbaumann/demosession_python_qgis#1]
Vielen Dank für die tolle Demosession!

Ist der Code des erwähnten eigenen locator providers (Adress-Suche) auch irgendwo verfügbar?

**Comment by thbaumann** [comment]
Danke für die Rückmeldung :)

Der erwähnte Locator Provider ist im Endeffekt ein Fork von https://github.com/rduivenvoorde/pdok_locatieserver_locator_filter, der dann an die hausinterne REST-API angepasst wurde. Insofern würde ich gerne auf dieses Repository verweisen, da die hausinterne Variante erst bereinigt/verallgemeinert werden müsste bevor man das online stellen könnte und im Vergleich zum pdok_locatieserver_locator_filter nicht viel mehr Infos beinhalten würde.

Wenn ich demnächst ein Refactoring des Plugins machen sollte würde ich mich allerdings mehr an dem swiss-locator von opengis orientieren, weil dieses Repo recht aktiv gepflegt/weiterentwickelt wird: https://github.com/opengisch/qgis-swiss-locator

**Comment by pathmapper** [comment]
Alles klar! Danke für die Links, schaue ich mir 'mal an.
